name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  |
        echo "A initial message"
        apt-get update -y && \
        apt-get install -y python3.9 && \
        apt-get install -y python3-pip &&\
        pip install --upgrade pip 
    - working-directory: ./app
    - run: |
        copy . /app
        pip install --no-cache-dir -r requirements.txt
        CMD ["python3", "train.py"]
        



