name: Run Training Pipeline

on: 
  push:
   branches: [ dev]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Run Training Script
      run: python src/train.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: trained-models
        path: runs/**/weights/*.pkl

    - name: Archive training results
      uses: actions/upload-artifact@v2
      with:
        name: training-results
        path: runs/**/train_results.csv

    