name: ML Pipeline

on: 
  push:
   branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print working directory
      run: pwd

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: src

    - name: Run Training Script
      run: python train.py
      working-directory: src

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: trained-models
          path: ${{ github.workspace }}/runs/**/weights/*.pkl
      
    - name: Archive training results
      uses: actions/upload-artifact@v2
      with:
          name: training-results
          path: ${{ github.workspace }}/runs/**/train_results.csv